management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,service-info,env,configprops,loggers,autoconfig,*
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    DB_CLOSE_DELAY: -1
    DB_CLOSE_ON_EXIT: FALSE
logging:
  level:
    org.springframework: INFO